Markt/Markt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('buyer/', include('buyer.urls')),
    path('seller/', include('seller.urls')),
]

Markt/buyer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'buyer'

urlpatterns = [
    path('dashboard/', views.display_buyer_dash, name="dashboard"),
    url(r'^dashboard/category/(?P<category_id>\d+)/$', views.display_buyer_cat, name="category"),
    url(r'^dashboard/item/(?P<item_id>\d+)/$', views.display_buyer_item, name="item"),
]

Markt/homepage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.display_home, name="home"),
    path('login/', views.display_login, name="login"),
    path('signup/', views.display_signup, name="signup"),
    path('dashboard/', views.display_dash_home, name="dash_home"),
    path('mailbox/', views.display_mail_home, name="mail_home"),
    url(r'^mailbox/mailview/(?P<mail_id>\d+)/$', views.display_mail, name="mail_view"),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Markt/seller/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve

from Markt import settings
from . import views


app_name = 'seller'

urlpatterns = [
    path('dashboard/', views.display_seller_dash, name="dashboard"),
    path(r'dashboard/item/edit/(?P<item_id>\d+)/$', views.display_seller_mod, name="mod"),
    # url(r'^dashboard/item/(?P<item_id>\d+)/$', views.display_seller_mod, name="mod"),
    url(r'^dashboard/listings/(?P<category_id>\d+)/$', views.display_seller_list, name="listings"),
    url(r'^dashboard/item/(?P<item_id>\d+)/$', views.display_seller_item, name="item"),


]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Markt/homepage/models.py
from django.db import models


class User(models.Model):
    name = models.CharField(max_length=50)
    bio = models.CharField(max_length=150)
    email_id = models.EmailField()
    password = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=10)
    share_email = models.BooleanField(default=True)
    share_phone = models.BooleanField(default=False)

Markt/homepage/views.py
from django.shortcuts import render, redirect, reverse
from urllib import request
from .models import User
from seller.models import Mail,Bid
import operator


def display_home(request):
    # use request.session to pass anything you need between views
    # delete sessions on pages that aren't dashboard pages to force logout
    # used to display variables within frontend

    request.session.flush()
    context = {
        'page_name': "Home",
    }

    return render(request, 'homepage/index.html', context)


def display_login(request):
    request.session.flush()
    if request.method == 'POST':
        context = {}
        email = request.POST['your_name']
        password = request.POST['your_pass']

        try:
            user = User.objects.get(email_id=email)
        except:
            context['errormessage'] = "This user is not registered"
            return render(request, 'homepage/login.html', context)

        if password != user.password:
            context['errormessage'] = "Password doesn't match"

        request.session['username'] = user.name
        request.session['userid'] = user.id
        return redirect(reverse('homepage:dash_home'))

    else:
        context = {
            'page_name': "Login",
        }
        return render(request, 'homepage/login.html', context)


def display_signup(request):
    context = {}
    request.session.flush()
    if request.method == 'POST':
        name = request.POST.get('name')
        email_id = request.POST.get('email')
        password = request.POST.get('pass')
        re_password = request.POST.get('re_pass')

        if password != re_password:
            context['errormessage'] = "Password doesn't match"
            return render(request, 'homepage/registration.html', context)

        try:
            user = User.objects.get(email_id=email_id)
            context['errormessage'] = "Email ID exists"
            return render(request, 'homepage/registration.html', context)
        except:
            user = User()
            user.name = name
            user.email_id = email_id
            user.password = password
            user.save()
            request.session['username'] = user.name
            request.session['userid'] = user.id
            return redirect(reverse('homepage:dash_home'))

    else:
        context = {
            'page_name': "Sign Up",
        }
        return render(request, 'homepage/registration.html', context)


def display_dash_home(request):
    if 'userid' not in request.session.keys() :
        return redirect(reverse('homepage:home'))
    user=User.objects.get(id=request.session['userid'])
    context = {
        'page_name': "Dashboard",
        'user':user,
    }
    if user.share_phone==True:
        context['shph']=True
    

    if request.method=="POST":
        user.name=request.POST['nameupd']
        user.phone_number=request.POST['phupd']
        user.bio=request.POST['bioupd']
        user.share_phone=False
        if len(request.POST.getlist('numshare'))==1:
            user.share_phone=True
        user.save()
        context['updated']=True

    return render(request, 'homepage/dashboard.html', context)


def display_mail_home(request):
    if 'userid' not in request.session.keys() :
        return redirect(reverse('homepage:home'))
    if request.method=="POST":
        del_mail=Mail.objects.get(id=request.POST['delm'])
        del_mail.delete()

    uid=request.session['userid']
    mails= Mail.objects.filter(recv_id=uid).order_by('-created')
    mails=list(mails)
    context = {
        'page_name': "Mailbox",
        'mails':mails,
    }
    


    return render(request, 'homepage/mailbox.html', context)


def display_mail(request,mail_id):

    if 'userid' not in request.session.keys() :
        return redirect(reverse('homepage:home'))
    mail=Mail.objects.get(id=mail_id)

    context = {
        'page_name': mail.bid_id.product_id.name, 
        'mail_title':  mail.bid_id.product_id.name,
        'mail_sender':  mail.sender_id.name,
        'mail':mail,
    }
    if mail.message_type==1:
        context['newbid']=True
    if mail.message_type==2:
        context['contact_reply']=True
        if mail.sender_id.share_phone==True:
            context['sharephone']=True
    if request.method=="POST":
        # TODO:
        #create a new mail to send back to person who sent it
        reply=Mail()
        reply.sender_id=mail.buyer_id
        reply.recv_id=mail.sender_id
        reply.bid_id=mail.bid_id
        reply.message_type=2
        reply.save()
        context['sending_done']=True


    return render(request, 'homepage/mail-view.html', context)

Markt/homepage/templates/homepage/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8">
    <title> {{page_name}} | Mar.kt </title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicons -->
    <link href="{% static 'homepage/img/favicon.png' %}" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed|Voltaire" rel="stylesheet">

    <!-- Theme css -->
    <link href="{% static 'homepage/css/theme.css' %}" rel="stylesheet">

    <!-- Custom css -->
    <link href="{% static 'homepage/css/index.css' %}" rel="stylesheet">
    <link href="{% static 'homepage/css/login.css' %}" rel="stylesheet">


    <!-- Bootstrap css -->
    <!-- <link rel="stylesheet" href="css/bootstrap.css"> -->
    <link href="{% static 'homepage/lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Libraries CSS Files -->
    <link href="{% static 'homepage/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'homepage/lib/owlcarousel/assets/owl.theme.default.min.css' %}" rel="stylesheet">
    <link href="{% static 'homepage/lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'homepage/lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'homepage/lib/modal-video/css/modal-video.min.css' %}" rel="stylesheet">

    <!-- Main Stylesheet File -->
    <link href="{% static 'homepage/css/style.css' %}" rel="stylesheet">
</head>

<body>

<header id="header" class="header header-hide">
    <div class="container">

        <div id="logo" class="pull-left">
            <a href="{% url 'homepage:home' %}"><img class="logo-image" id="homepage-logo" src="{% static 'homepage/img/logo3.png' %}" alt="" title="homelogo" /></a>
        </div>

        <nav id="nav-menu-container">
            <ul class="nav-menu">

                <li class="menu-active"><a href="{% url 'homepage:home' %}">Home</a></li>

                <li class="menu-active"><a href="{% url 'homepage:signup' %}">Register</a></li>

            </ul>
        </nav><!-- #nav-menu-container -->
    </div>
</header><!-- #header -->

<!--==========================
  Hero Section
============================-->
<section id="hero" class="wow fadeIn">
    <div class="hero-container">

        <section class="sign-in">
            <div class="container" id="login-box">
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="{% static 'homepage/img/signin-image.jpg' %}" alt="sing up image"></figure>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Login</h2>
                        <form method="POST" class="register-form" id="login-form">
                          {% csrf_token %}
                          {% if errormessage %}
                            <div class="form-group text-danger">
                                {{ errormessage }}
                            </div>
                            {% endif %}
                            <div class="form-group">
                                <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="email" name="your_name" id="your_name" maxlength="50" placeholder="Email ID" required/>
                            </div>
                            <div class="form-group">
                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="your_pass" id="your_pass" maxlength="20" placeholder="Password" required/>
                            </div>
                            <!-- <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                            </div> -->
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/><br>
                                <a href="{% url 'homepage:signup' %}" class="signup-image-link">Create an account</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>

    </div>
</section><!-- #hero -->

<footer class="footer">
    <div class="container" id="footer-container">
        <div class="row">

            <div class="col-md-12 col-lg-4">
                <div class="footer-logo">

                    <a class="navbar-brand" href="#"><img src="{% static 'homepage/img/logo3.png' %}" class="logo-image" id="footer-logo"></a>
                    <p>A college sales portal<br>By students; For students</p>

                </div>
            </div>



            <div class="col-sm-6 col-md-3 col-lg-2">
                <div class="list-menu">

                    <h4>Support</h4>

                    <ul class="list-unstyled">
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>

                </div>
            </div>
        </div>
    </div>

    <div class="copyrights">
        <div class="container">
            <p>&copy; Copyrights Mark.kt. All rights reserved.</p>
        </div>
    </div>

</footer>



<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>

<!--Custom JS and JQuery-->
<script src="{% static 'homepage/jquery/jquery.min.js' %} "></script>
<script src="{% static 'homepage/js/login.js' %}"></script>

<!-- JavaScript Libraries -->
<script src="{% static 'homepage/lib/jquery/jquery.min.js' %}"></script>
<script src="{% static 'homepage/lib/jquery/jquery-migrate.min.js' %}"></script>
<script src="{% static 'homepage/lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'homepage/lib/superfish/hoverIntent.js' %}"></script>
<script src="{% static 'homepage/lib/superfish/superfish.min.js' %}"></script>
<script src="{% static 'homepage/lib/easing/easing.min.js' %}"></script>
<script src="{% static 'homepage/lib/modal-video/js/modal-video.js' %}"></script>
<script src="{% static 'homepage/lib/owlcarousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'homepage/lib/wow/wow.min.js' %}"></script>

<!-- Template Main Javascript File -->
<script src="{% static 'homepage/js/main.js' %}"></script>

</body>
</html>

Markt/homepage/templates/homepage/mail-view.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
  <meta charset="utf-8" />

  <!-- Favicons -->
  <link href="{% static 'homepage/img/favicon.png' %}" rel="icon"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>
    {{page_name}} | Mar.kt
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed|Voltaire" rel="stylesheet">
  <link href="{% static 'homepage/css/font-awesome.min.css' %}" rel="stylesheet">
  
  <!-- CSS Files -->
  <link href="{% static 'homepage/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'homepage/css/paper-dashboard.css' %}" rel="stylesheet" />

   <!-- Theme css -->
   <link href="{% static 'homepage/css/theme.css' %}" rel="stylesheet">

   <!-- Custom css -->
   <link href="{% static 'homepage/css/dash.css' %}" rel="stylesheet">

  
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="white" data-active-color="danger">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <!-- <a href="http://www.creative-tim.com" class="simple-text logo-mini">
          <div class="logo-image-small">
            <img src="../assets/img/logo-small.png">
          </div>
        </a> -->
        <a href="{% url 'homepage:dash_home' %}" class="simple-text logo-normal">
          <div class="logo-image-big logo-image dash-logo">
            <img src="{% static 'homepage/img/logo3.png' %}">
          </div>
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li  id="dbhome">
            <a href="{% url 'homepage:dash_home' %}">
              <i class="nc-icon nc-laptop"></i>
              <p>Dashboard Home</p>
            </a>
          </li>
          <li  class="active" id="mail">
            <a href="{% url 'homepage:mail_home' %}">
              <i class="nc-icon nc-email-85"></i>
              <p>Mailbox</p>
            </a>
          </li>
          <li id="seller">
            <a href="#">
              <i class="nc-icon nc-money-coins"></i>
              <p>Seller Dashboard</p>
            </a>
          </li>
          <li id="buyer">
            <a href="{% url 'buyer:dashboard' %}">
              <i class="nc-icon nc-bag-16"></i>
              <p>Buyer Dashboard</p>
            </a>
          </li>
         
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#pablo">{{ page_name }}</a>
          </div>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
              <form>
                <div class="input-group no-border">
                  
                </div>
              </form>
              <ul class="navbar-nav">
                <li class="nav-item btn-rotate dropdown">
                  <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="nc-icon nc-user-run"></i>
                    <p>
                      <span class="d-lg-none d-md-block">Some Actions</span>
                    </p>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'homepage:home' %}">Logout</a>
                  </div>
                </li>
                
              </ul>
            </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <!-- <div class="panel-header panel-header-lg">
  
  <canvas id="bigDashboardChart"></canvas>
  
  
</div> -->
<div class="content">
  <div class="row">
      <div class="col-md-12">
          <div class="card ">
            <div class="card-header ">
              <h5 class="card-title">{{ mail_title }}</h5>
              <p class="card-category"> {{ mail_sender }}</p>
            </div>
            <div class="card-body ">
              {% if sending_done %}
              <div class="text-success">
                Your Reply has been sent<br>
              </div>
              {% endif %}
            <form method="POST">
              {% csrf_token %}
              {% if newbid %}
              <p> Hello {{ mail.recv_id.name }}<br>I was interested in bidding on your <a href="{% url 'seller:item' mail.bid_id.product_id.id %}"> {{ mail.bid_id.product_id.name }} </a> and am currently willing to pay Rs.{{ mail.bid_id.price }}.<br>
              Please share your contact details if you are interested in my offer by clicking the button :
            <button type="submit">Share my details</button></p>
              {% endif %}
              {% if contact_reply %}
              Hello {{ mail.recv_id.name }}
              <br> {{ mail_sender }} has shared their contact details with regards to your bid of Rs.{{ mail.bid_id.price }} on the item <a href="{% url 'buyer:item' mail.bid_id.product_id.id %}"> {{ mail.bid_id.product_id.name }} </a>. <br>
              You can reach them at: <br>
              Email: {{ mail.sender_id.email_id }}<br>
              {% if sharephone %}
              Phone Number : {{ mail.sender_id.phone_number }}
              {% endif %}
              {% endif %}
            </form>
            </div>
            <div class="card-footer ">
              <hr>
              <div class="stats">
                
              </div>
            </div>
          </div>
          </div>
    </div>
      <footer class="footer footer-black  footer-white ">
        <div class="container-fluid">
          <div class="row">
            <nav class="footer-nav">
              <!-- <ul>
                <li>
                  <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>
                </li>
                <li>
                  <a href="http://blog.creative-tim.com/" target="_blank">Blog</a>
                </li>
                <li>
                  <a href="https://www.creative-tim.com/license" target="_blank">Licenses</a>
                </li>
              </ul> -->
            </nav>
            <div class="credits ml-auto">
              <span class="copyright">
                ©
                <script>
                  document.write(new Date().getFullYear())
                </script> Mark.kt. All rights reserved.
              </span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'homepage/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'homepage/js/popper.min.js' %}"></script>
  <script src="{% static 'homepage/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'homepage/js/perfect-scrollbar.jquery.min.js' %}"></script>
  
  <!-- Chart JS -->
  <script src="{% static 'homepage/js/chartjs.min.js' %}"></script>
  
  <!--  Notifications Plugin    -->
  <script src="{% static 'homepage/js/bootstrap-notify.js' %}"></script>
  
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'homepage/js/dash.js' %}" type="text/javascript"></script>
  
 
</body>

</html>

Markt/homepage/templates/homepage/mailbox.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
  <meta charset="utf-8" />

  <!-- Favicons -->
  <link href="{% static 'homepage/img/favicon.png' %}" rel="icon"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>
    {{page_name}} | Mar.kt
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed|Voltaire" rel="stylesheet">
  <link href="{% static 'homepage/css/font-awesome.min.css' %}" rel="stylesheet">
  
  <!-- CSS Files -->
  <link href="{% static 'homepage/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'homepage/css/paper-dashboard.css' %}" rel="stylesheet" />

   <!-- Theme css -->
   <link href="{% static 'homepage/css/theme.css' %}" rel="stylesheet">

   <!-- Custom css -->
   <link href="{% static 'homepage/css/dash.css' %}" rel="stylesheet">

  
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="white" data-active-color="danger">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <!-- <a href="http://www.creative-tim.com" class="simple-text logo-mini">
          <div class="logo-image-small">
            <img src="../assets/img/logo-small.png">
          </div>
        </a> -->
        <a href="{% url 'homepage:dash_home' %}" class="simple-text logo-normal">
          <div class="logo-image-big logo-image dash-logo">
            <img src="{% static 'homepage/img/logo3.png' %}">
          </div>
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li  id="dbhome">
            <a href="{% url 'homepage:dash_home' %}">
              <i class="nc-icon nc-laptop"></i>
              <p>Dashboard Home</p>
            </a>
          </li>
          <li  class="active" id="mail">
            <a href="{% url 'homepage:mail_home' %}">
              <i class="nc-icon nc-email-85"></i>
              <p>Mailbox</p>
            </a>
          </li>
          <li id="seller">
            <a href="{% url 'seller:dashboard' %}">
              <i class="nc-icon nc-money-coins"></i>
              <p>Seller Dashboard</p>
            </a>
          </li>
          <li id="buyer">
            <a href="{% url 'buyer:dashboard' %}">
              <i class="nc-icon nc-bag-16"></i>
              <p>Buyer Dashboard</p>
            </a>
          </li>
         
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="">{{ page_name }}</a>
          </div>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
              <form>
                <div class="input-group no-border">
                  
                </div>
              </form>
              <ul class="navbar-nav">
                <li class="nav-item btn-rotate dropdown">
                  <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="nc-icon nc-user-run"></i>
                    <p>
                      <span class="d-lg-none d-md-block">Some Actions</span>
                    </p>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'homepage:home' %}">Logout</a>
                  </div>
                </li>
                
              </ul>
            </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <!-- <div class="panel-header panel-header-lg">
  
  <canvas id="bigDashboardChart"></canvas>
  
  
</div> -->
<div class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Inbox &nbsp; <i class="nc-icon nc-refresh-69 "></i>
          </h4>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table">
              <thead class=" text-primary">
                <th>
                  Sender
                </th>
                <th>
                  Listing
                </th>
                <th>
                  Bid Amount
                </th>
                <th>
                  Delete Mail
                </th>
              </thead>
              <tbody>
              {% for mail in mails %}    
                <tr>
                  <td>
                    {{ mail.sender_id.name }}
                  </td>
                  <td>
                      <a href="{% url 'homepage:mail_view' mail.id %}">
                    {{ mail.bid_id.product_id.name }}
                  </a>
                  </td>
                  <td>
                      
                    {{ mail.bid_id.price }}
                  
                  </td>
                  <td>

                  <form method="POST">
                    {% csrf_token %}
                    <button type="submit" value={{ mail.id }} name="delm">Delete Mail</button>
                  </form>
                    
                  </td>
                </tr>
              {% endfor %}
                
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    </div>
      <footer class="footer footer-black  footer-white ">
        <div class="container-fluid">
          <div class="row">
            <nav class="footer-nav">
              <!-- <ul>
                <li>
                  <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>
                </li>
                <li>
                  <a href="http://blog.creative-tim.com/" target="_blank">Blog</a>
                </li>
                <li>
                  <a href="https://www.creative-tim.com/license" target="_blank">Licenses</a>
                </li>
              </ul> -->
            </nav>
            <div class="credits ml-auto">
              <span class="copyright">
                ©
                <script>
                  document.write(new Date().getFullYear())
                </script> Mark.kt. All rights reserved.
              </span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'homepage/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'homepage/js/popper.min.js' %}"></script>
  <script src="{% static 'homepage/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'homepage/js/perfect-scrollbar.jquery.min.js' %}"></script>
  
  <!-- Chart JS -->
  <script src="{% static 'homepage/js/chartjs.min.js' %}"></script>
  
  <!--  Notifications Plugin    -->
  <script src="{% static 'homepage/js/bootstrap-notify.js' %}"></script>
  
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'homepage/js/dash.js' %}" type="text/javascript"></script>
  
 
</body>

</html>

Markt/homepage/templates/homepage/sample.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>sample page</title>
  </head>
  <body>Hi {{email_id}} !!</body>
</html>