Markt/Markt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('buyer/', include('buyer.urls')),
    path('seller/', include('seller.urls')),
]

Markt/buyer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'buyer'

urlpatterns = [
    path('dashboard/', views.display_buyer_dash, name="dashboard"),
    url(r'^dashboard/category/(?P<category_id>\d+)/$', views.display_buyer_cat, name="category"),
    url(r'^dashboard/item/(?P<item_id>\d+)/$', views.display_buyer_item, name="item"),
]

Markt/homepage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.display_home, name="home"),
    path('login/', views.display_login, name="login"),
    path('signup/', views.display_signup, name="signup"),
    path('dashboard/', views.display_dash_home, name="dash_home"),
    path('mailbox/', views.display_mail_home, name="mail_home"),
    url(r'^mailbox/mailview/(?P<mail_id>\d+)/$', views.display_mail, name="mail_view"),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Markt/seller/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.static import serve

from Markt import settings
from . import views


app_name = 'seller'

urlpatterns = [
    path('dashboard/', views.display_seller_dash, name="dashboard"),
    path(r'dashboard/item/edit/(?P<item_id>\d+)/$', views.display_seller_mod, name="mod"),
    # url(r'^dashboard/item/(?P<item_id>\d+)/$', views.display_seller_mod, name="mod"),
    url(r'^dashboard/listings/(?P<category_id>\d+)/$', views.display_seller_list, name="listings"),
    url(r'^dashboard/item/(?P<item_id>\d+)/$', views.display_seller_item, name="item"),


]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Markt/seller/models.py
from django.db import models

from homepage.models import User

from buyer.models import Product


class Bid(models.Model):
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='p_id')
    buyer_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='b_id')
    price = models.DecimalField(max_digits=6, decimal_places=2)
    timestamp = models.DateTimeField(auto_now=True)


class Mail(models.Model):
    sender_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='buy_id')
    recv_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='vend_id')
    bid_id = models.ForeignKey(Bid, on_delete=models.CASCADE)
    message_type = models.PositiveSmallIntegerField()
    created = models.DateTimeField(auto_now_add=True)

Markt/seller/views.py
from buyer.models import Product
from django.shortcuts import render, redirect, reverse
from homepage.models import User
from seller.models import Bid
from django.core.files.storage import FileSystemStorage
from Markt import settings
import os


# Create your views here.

def display_seller_dash(request):
    if 'userid' not in request.session.keys():
        return redirect(reverse('homepage:home'))
    context = {
        'page_name': "Seller Dashboard",
        "cat_id": 9,
    }
    userid = request.session['userid']
    products = Product.objects.filter(vendor_id=userid).order_by('-current_high_bid')[:3]
    products = list(products)
    while len(products) < 3:
        products.append(None)
    if products[0] is not None:
        context['item1'] = products[0]
    if products[0] is not None:
        context['item2'] = products[1]
    if products[0] is not None:
        context['item3'] = products[2]

    return render(request, 'seller/seller-dashboard.html', context)


def display_seller_list(request, category_id):
    if 'userid' not in request.session.keys():
        return redirect(reverse('homepage:home'))
    context = {
        'page_name': "Seller Listings",
        'category': "Generic Category",
        # 'base_bid': 100,
        # 'high': 300,
        # 'id':0,
    }

    items = Product.objects.filter(vendor_id=request.session['userid'])
    context['items'] = items
    return render(request, 'seller/seller-listings.html', context)


def display_seller_item(request, item_id):
    if 'userid' not in request.session.keys():
        return redirect(reverse('homepage:home'))
    product = Product.objects.get(id=item_id)
    context = {'page_name': "Item Display", 'product': product,
               'bids': list(Bid.objects.filter(product_id=product).order_by('-price'))}

    return render(request, 'seller/seller-item.html', context)


def display_seller_mod(request, item_id):
    if 'userid' not in request.session.keys():
        return redirect(reverse('homepage:home'))

    context = {
        'username': request.session['username']
    }

    # to modify a product
    if item_id != "-1":
        product = Product.objects.get(id=item_id)
        context['product'] = product
        context['delete_button'] = True
        context['button_text'] = "Modify Product"
        context['editprod'] = True
        if product.category == 'Textbooks':
            context['cat_id'] = 1
        elif product.category == 'QPs':
            context['cat_id'] = 2
        elif product.category == 'Notes':
            context['cat_id'] = 3
        elif product.category == 'Furniture':
            context['cat_id'] = 4

        if request.method == "POST" and 'delete-listing' in request.POST:
            product.delete()
            return redirect(reverse('seller:dashboard'))

        if request.method == 'POST' and context['button_text'] == 'Modify Product':
            product.name = request.POST['name']
            product.category = request.POST['category']
            product.description = request.POST['description']
            product.minimum_bid = request.POST['base_bid']
            if product.category == 'Textbooks':
                product.cat_id = 1
            elif product.category == 'QPs':
                product.cat_id = 2
            elif product.category == 'Notes':
                product.cat_id = 3
            elif product.category == 'Furniture':
                product.cat_id = 4
            product.save()
            return redirect(reverse('seller:dashboard'))

    if item_id == '-1':
        context['product'] = Product()
        context['button_text'] = "Add Product"
        context['cat_id'] = 1
        context['newprod'] = True

        if request.method == 'POST' and context['button_text'] == 'Add Product':
            context['category'] = request.POST['category']
            user = User.objects.get(id=request.session['userid'])
            product = Product()
            product.name = request.POST['name']
            product.category = request.POST['category']
            product.vendor_id = user
            product.description = request.POST['description']
            product.minimum_bid = request.POST['base_bid']
            product.current_high_bid = 0
            myfile = request.FILES['filename']
            if myfile is None:
                context['errorm'] = True
                return render(request, 'seller/seller-mod.html', context)

            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            product.image_link = fs.url(filename)
            if product.category == 'Textbooks':
                product.cat_id = 1
            elif product.category == 'QPs':
                product.cat_id = 2
            elif product.category == 'Notes':
                product.cat_id = 3
            elif product.category == 'Furniture':
                product.cat_id = 4
            product.save()
            return redirect(reverse('seller:dashboard'))

        if request.method == 'POST' and "img-submit" in request.POST:
            context['category'] = request.POST['category']
            user = User.objects.get(id=request.session['userid'])
            product = Product()
            product.name = request.POST['name']
            product.category = request.POST['category']
            product.vendor_id = user
            product.description = request.POST['description']
            product.minimum_bid = request.POST['base_bid']
            product.current_high_bid = 0
            myfile = request.FILES['filename']
            if myfile is None:
                context['errorm'] = True
                return render(request, 'seller/seller-mod.html', context)

            fs = FileSystemStorage()

            save_path = os.path.join(settings.MEDIA_ROOT, 'uploads', myfile.name)
            filename = fs.save(save_path, myfile)
            product.image_link = fs.url(filename)
            product.save()
            return redirect(reverse('seller:dashboard'))

    return render(request, 'seller/seller-mod.html', context)

Markt/seller/templates/seller/seller-dashboard.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
  <meta charset="utf-8" />

  <!-- Favicons -->
  <link href="{% static 'homepage/img/favicon.png' %}" rel="icon"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>
    {{page_name}} | Mar.kt
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed|Voltaire" rel="stylesheet">
  <link href="{% static 'homepage/css/font-awesome.min.css' %}" rel="stylesheet">

  <!-- CSS Files -->
  <link href="{% static 'homepage/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'homepage/css/paper-dashboard.css' %}" rel="stylesheet" />

   <!-- Theme css -->
   <link href="{% static 'homepage/css/theme.css' %}" rel="stylesheet">

   <!-- Custom css -->
   <link href="{% static 'homepage/css/dash.css' %}" rel="stylesheet">
   <link href="{% static 'buyer/css/buyer-dashboard.css' %}" rel="stylesheet">


</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="white" data-active-color="danger">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <!-- <a href="http://www.creative-tim.com" class="simple-text logo-mini">
          <div class="logo-image-small">
            <img src="../assets/img/logo-small.png">
          </div>
        </a> -->
        <a href="{% url 'homepage:dash_home' %}" class="simple-text logo-normal">
          <div class="logo-image-big logo-image dash-logo">
            <img src="{% static 'homepage/img/logo3.png' %}">
          </div>
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li  id="dbhome">
            <a href="{% url 'homepage:dash_home' %}">
              <i class="nc-icon nc-laptop"></i>
              <p>Dashboard Home</p>
            </a>
          </li>
          <li  id="mail">
            <a href="{% url 'homepage:mail_home' %}">
              <i class="nc-icon nc-email-85"></i>
              <p>Mailbox</p>
            </a>
          </li>
          <li class="active" id="seller">
            <a href="{% url 'seller:dashboard' %}">
              <i class="nc-icon nc-money-coins"></i>
              <p>Seller Dashboard</p>
            </a>
          </li>
          <li id="buyer">
            <a href="{% url 'buyer:dashboard' %}">
              <i class="nc-icon nc-bag-16"></i>
              <p>Buyer Dashboard</p>
            </a>
          </li>

        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#pablo"> Seller Dashboard</a>
          </div>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
              <form>
                <div class="input-group no-border">
                  
                </div>
              </form>
              <ul class="navbar-nav">
                <li class="nav-item btn-rotate dropdown">
                  <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="nc-icon nc-user-run"></i>
                    <p>
                      <span class="d-lg-none d-md-block">Some Actions</span>
                    </p>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'homepage:home' %}">Logout</a>
                  </div>
                </li>
                
              </ul>
            </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <!-- <div class="panel-header panel-header-lg">

  <canvas id="bigDashboardChart"></canvas>


</div> -->
      <div class="content">
        <div class="row">
          <div class="col-sm-6">
              <a href="{% url 'seller:listings' cat_id %}">
            <div class="card card-stats">
              <div class="card-body ">
                <div class="row">
                  <div class="col-5 col-md-4">
                    <div class="icon-big text-left icon-warning">
                      <i class="nc-icon nc-paper"></i>
                    </div>
                  </div>
                  <div class="col-7 col-md-8">
                    <div class="numbers">
                      <p class="card-category">Listings</p>
                      <p class="card-title">My Products
                        <p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            </a>
          </div>
          <div class="col-sm-6">
            <a href="{% url 'seller:mod' -1 %}">
            <div class="card card-stats">
              <div class="card-body ">
                <div class="row">
                  <div class="col-5 col-md-4">
                    <div class="icon-big text-left icon-warning">
                      <i class="nc-icon nc-simple-add"></i>
                    </div>
                  </div>
                  <div class="col-7 col-md-8">
                    <div class="numbers">
                      <p class="card-category"> New Listing</p>
                      <p class="card-title">Add Product
                        <p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </a>
          </div>
          <!-- <div class="col-sm-4">
            <div class="card card-stats">
              <div class="card-body ">
                <div class="row">
                  <div class="col-5 col-md-4">
                    <div class="icon-big text-left icon-warning">
                      <i class="nc-icon nc-money-coins"></i>
                    </div>
                  </div>
                  <div class="col-7 col-md-8">
                    <div class="numbers">
                      <p class="card-category">Financials</p>
                      <p class="card-title">My Earnings
                        <p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div> -->
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card ">
              <div class="card-header ">
                <h5 class="card-title">Your Hottest Listings</h5>
                <p class="card-category">Find out which of your products buyers love</p>
              </div>
              <div class="card-body ">
                <div class="row">
                  {% if item1 %}
                  <a href="{% url 'seller:mod' item1.id %}">
                  <div class="col-sm-4">
                      <div class="card card-stats">
                        <div class="card-body">
                          <div class="row text-center">
                            <div class="col-4">
                                <img class="product_img" src="{{ item1.image_link }}">
                            </div>
                            <div class="col-8">
                              <div class="numbers">
                                <p class="card-category">{{ item1.category }}</p>
                                <p class="card-title">{{ item1.name }}
                                  <p>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card-footer text-center">
                          <hr>
                          Base Bid : {{ item1.minimum_bid }} | Highest : {{ item1.current_high_bid }}
                        </div>
                      </div>
                  </div>
                </a>
                  {% endif %}
                  {% if item2 %}
                  <a href="{% url 'seller:mod' item2.id %}">
                  <div class="col-sm-4">
                      <div class="card card-stats">
                        <div class="card-body">
                          <div class="row text-center">
                            <div class="col-4">
                                <img class="product_img" src="{{ item2.image_link }}">
                            </div>
                            <div class="col-8">
                              <div class="numbers">
                                <p class="card-category">{{ item2.category }}</p>
                                <p class="card-title">{{ item2.name }}
                                  <p>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card-footer text-center">
                          <hr>
                          Base Bid : {{ item2.minimum_bid }} | Highest : {{ item2.current_high_bid }}
                        </div>
                      </div>
                  </div>
                </a>
                  {% endif %}
                  {% if item3 %}
                  <a href="{% url 'seller:mod' item3.id %}">
                  <div class="col-sm-4">
                      <div class="card card-stats">
                        <div class="card-body">
                          <div class="row text-center">
                            <div class="col-4">
                                <img class="product_img" src="{{ item3.image_link }}">
                            </div>
                            <div class="col-8">
                              <div class="numbers">
                                <p class="card-category">{{ item3.category }}</p>
                                <p class="card-title">{{ item3.name }}
                                  <p>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div class="card-footer text-center">
                          <hr>
                          Base Bid : {{ item3.minimum_bid }} | Highest : {{ item3.current_high_bid }}
                        </div>
                      </div>
                  </div>
                </a>
                  {% endif %}
                  
                 
                </div>
              </div>
              <div class="card-footer ">
                <hr>
              </div>
            </div>
          </div>
        </div>
      </div>
      <footer class="footer footer-black  footer-white ">
        <div class="container-fluid">
          <div class="row">
            <nav class="footer-nav">
              <!-- <ul>
                <li>
                  <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>
                </li>
                <li>
                  <a href="http://blog.creative-tim.com/" target="_blank">Blog</a>
                </li>
                <li>
                  <a href="https://www.creative-tim.com/license" target="_blank">Licenses</a>
                </li>
              </ul> -->
            </nav>
            <div class="credits ml-auto">
              <span class="copyright">
                ©
                <script>
                  document.write(new Date().getFullYear())
                </script> Mark.kt. All rights reserved.
              </span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'homepage/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'homepage/js/popper.min.js' %}"></script>
  <script src="{% static 'homepage/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'homepage/js/perfect-scrollbar.jquery.min.js' %}"></script>

  <!-- Chart JS -->
  <script src="{% static 'homepage/js/chartjs.min.js' %}"></script>

  <!--  Notifications Plugin    -->
  <script src="{% static 'homepage/js/bootstrap-notify.js' %}"></script>

  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'homepage/js/dash.js' %}" type="text/javascript"></script>


</body>

</html>

Markt/seller/templates/seller/seller-item.html
<!DOCTYPE html>
<html lang="en">

{% load static %}
<head>
  <meta charset="utf-8" />

  <!-- Favicons -->
  <link href="{% static 'homepage/img/favicon.png' %}" rel="icon"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>
    {{ product.name }} | Mar.kt
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed|Voltaire" rel="stylesheet">
  <link href="{% static 'homepage/css/font-awesome.min.css' %}" rel="stylesheet">

  <!-- CSS Files -->
  <link href="{% static 'homepage/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'homepage/css/paper-dashboard.css' %}" rel="stylesheet" />

   <!-- Theme css -->
   <link href="{% static 'homepage/css/theme.css' %}" rel="stylesheet">

   <!-- Custom css -->
   <link href="{% static 'homepage/css/dash.css' %}" rel="stylesheet">
   <link href="{% static 'seller/css/seller-item.css' %}" rel="stylesheet">


</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="white" data-active-color="danger">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <!-- <a href="http://www.creative-tim.com" class="simple-text logo-mini">
          <div class="logo-image-small">
            <img src="../assets/img/logo-small.png">
          </div>
        </a> -->
        <a href="{% url 'homepage:dash_home' %}" class="simple-text logo-normal">
          <div class="logo-image-big logo-image dash-logo">
            <img src="{% static 'homepage/img/logo3.png' %}">
          </div>
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li  id="dbhome">
            <a href="{% url 'homepage:dash_home' %}">
              <i class="nc-icon nc-laptop"></i>
              <p>Dashboard Home</p>
            </a>
          </li>
          <li  id="mail">
            <a href="{% url 'homepage:mail_home' %}">
              <i class="nc-icon nc-email-85"></i>
              <p>Mailbox</p>
            </a>
          </li>
          <li id="seller" class="active">
            <a href="{% url 'seller:dashboard' %}">
              <i class="nc-icon nc-money-coins"></i>
              <p>Seller Dashboard</p>
            </a>
          </li>
          <li id="buyer">
            <a href="{% url 'buyer:dashboard' %}">
              <i class="nc-icon nc-bag-16"></i>
              <p>Buyer Dashboard</p>
            </a>
          </li>

        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <div class="navbar-brand">
            <a href="{% url 'buyer:dashboard' %}"> Seller Dashboard </a> <a href="{% url 'buyer:category' product.cat_id %}"> | {{ product.category }}</a> <a href=""> | {{ product.name  }}</a>
          </div>
          </div>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
              <form>
                <div class="input-group no-border">
                  
                </div>
              </form>
              <ul class="navbar-nav">
                <li class="nav-item btn-rotate dropdown">
                  <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="nc-icon nc-user-run"></i>
                    <p>
                      <span class="d-lg-none d-md-block">Some Actions</span>
                    </p>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'homepage:home' %}">Logout</a>
                  </div>
                </li>
                
              </ul>
            </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <!-- <div class="panel-header panel-header-lg">

  <canvas id="bigDashboardChart"></canvas>


</div> -->
      <div class="content">
        <div class="row">
          <div class="col-sm-4">
            <div class="card card-stats">
              <div class="card-body ">
                <div class="row">
                    <img class="product_img" src="{{ product.image_link }}">
                </div>
              </div>
            </div>
          </div>
          <div class="col-sm-8">
              <div class="card card-stats">
                <div class="card-body ">
                  <div class="row">
                    <div class="col-1"></div>
                    <div class="col-8">
                      <div class="text-left">
                        <p class="title_custom">{{ product.name }} </p>
                        <p class="category_custom">{{ product.category }}</p>
                        <p class="category_custom">Sold by {{ product.vendor_id.name }}</p>
                        <br>
                        <p class="description_custom">{{product.description}}
                          </p>
                        <hr>
                        <p class="title_custom">Base Bid : {{ product.minimum_bid }} | Highest : {{ product.current_high_bid }}  </p>
                        </div>
                      </div>
                      <div class="text-right">
                      <a href="{% url 'seller:mod' product.id %}" name="modify-listing" id="mod-list"><button>Modify Listing</button></a></div>


                      </div>
                      <div class="col-2"></div>
                    </div>
                  </div>
                </div>
              </div>

        <div class="row">
            <div class="col-sm-12">
              <div class="card card-stats">
                <div class="card-body ">
                  <div class="row">
                      <div class="col-12 text-left">
                          <table class="table">
                            <thead class=" text-primary">
                              <th>
                                Bid
                              </th>
                              <th>
                                Buyer
                              </th>
                              <th >
                                Timestamp
                              </th>
                            </thead>
                            <tbody>
                            {% for bid in bids %}
                              <tr>
                                <td>
                                  {{ bid.price }}
                                </td>
                                <td>
                                  {{ bid.buyer_id.name }}
                                </td>
                                <td >
                                  {{ bid.timestamp }}
                                </td>
                              </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                        </div>
                  </div>
                </div>
              </div>
            </div>


          </div>

      </div>
      <footer class="footer footer-black  footer-white ">
        <div class="container-fluid">
          <div class="row">
            <nav class="footer-nav">
              <!-- <ul>
                <li>
                  <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>
                </li>
                <li>
                  <a href="http://blog.creative-tim.com/" target="_blank">Blog</a>
                </li>
                <li>
                  <a href="https://www.creative-tim.com/license" target="_blank">Licenses</a>
                </li>
              </ul> -->
            </nav>
            <div class="credits ml-auto">
              <span class="copyright">
                ©
                <script>
                  document.write(new Date().getFullYear())
                </script> Mark.kt. All rights reserved.
              </span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'homepage/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'homepage/js/popper.min.js' %}"></script>
  <script src="{% static 'homepage/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'homepage/js/perfect-scrollbar.jquery.min.js' %}"></script>

  <!-- Chart JS -->
  <script src="{% static 'homepage/js/chartjs.min.js' %}"></script>

  <!--  Notifications Plugin    -->
  <script src="{% static 'homepage/js/bootstrap-notify.js' %}"></script>

  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'homepage/js/dash.js' %}" type="text/javascript"></script>


</body>

</html>